version: '2'

services:
  suggested:
    build: .
    depends_on:
      - 'postgres'
      - 'redis'
    ports: 
      - '3001:3001'

  postgres:
    image: postgres:latest

  redis:
    image: redis:latest
